services:
  api:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      # O "@db:1521" faz a API achar o Oracle dentro da rede do Docker
      - SPRING_DATASOURCE_URL=jdbc:oracle:thin:@//db:1521/XEPDB1
      - SPRING_DATASOURCE_USERNAME=RM565020
      - SPRING_DATASOURCE_PASSWORD=190207
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update

  db:
    image: gvenzl/oracle-xe
    ports:
      - "1521:1521"
    environment:
      - ORACLE_PASSWORD=190207
    volumes:
      - oracledata:/opt/oracle/oradata

volumes:
  oracledata: