# ==============================================================
# CONFIGURAÇÕES DO BANCO DE DADOS ORACLE (FIAP)
# ==============================================================

# URL de conexão (Substitua o host e o serviço pelo que a FIAP te passou, se for diferente)
spring.datasource.url=jdbc:oracle:thin:@oracle.fiap.com.br:1521:ORCL

# Suas credenciais (Normalmente o RM e a senha do portal)
spring.datasource.username=RM565020
spring.datasource.password=190207

# Driver oficial do Oracle
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

# ==============================================================
# CONFIGURAÇÕES DO JPA E HIBERNATE
# ==============================================================

# Diz para o Spring usar as regras e o SQL específico do Oracle 12c+
spring.jpa.database-platform=org.hibernate.dialect.OracleDialect

# Estratégia de criação de tabelas:
# "update" -> Cria as tabelas se não existirem e atualiza se você mudar algo na Entidade Java.
spring.jpa.hibernate.ddl-auto=update

# Mostra o SQL gerado no console (Ótimo para debugar e ver o que o Java está fazendo no banco)
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ==============================================================
# CONFIGURAÇÕES DA APLICAÇÃO
# ==============================================================
spring.application.name=clyvovet
server.port=8080

# Força o Spring e o Swagger a detalharem falhas de mapeamento e inicialização no console
logging.level.org.springdoc=DEBUG
logging.level.org.springframework.web=DEBUG