-- 1. Criação do User (Segurança)
CREATE TABLE tb_user (
                         id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                         username VARCHAR2(255) NOT NULL UNIQUE,
                         password VARCHAR2(255) NOT NULL,
                         role VARCHAR2(20) NOT NULL
);

-- 2. Criação do Tutor
CREATE TABLE tb_tutor (
                          id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                          nome_completo VARCHAR2(100) NOT NULL,
                          cpf VARCHAR2(14) NOT NULL UNIQUE,
                          telefone VARCHAR2(20),
                          email VARCHAR2(100) NOT NULL UNIQUE,
                          foto_url VARCHAR2(255),
                          user_id NUMBER UNIQUE,
    -- Colunas do @Embedded Endereco (ajuste se seus nomes de campo forem diferentes)
                          logradouro VARCHAR2(255),
                          numero VARCHAR2(20),
                          bairro VARCHAR2(100),
                          cidade VARCHAR2(100),
                          estado VARCHAR2(2),
                          cep VARCHAR2(9),
                          CONSTRAINT fk_tutor_user FOREIGN KEY (user_id) REFERENCES tb_user(id)
);

-- 3. Criação do Veterinário (se for implementado agora)
CREATE TABLE tb_veterinario (
                                id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                nome VARCHAR2(100) NOT NULL,
                                crmv VARCHAR2(20) NOT NULL UNIQUE,
                                user_id NUMBER UNIQUE,
                                CONSTRAINT fk_vet_user FOREIGN KEY (user_id) REFERENCES tb_user(id)
);

-- 4. Criação do Pet
CREATE TABLE tb_pet (
                        id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        nome VARCHAR2(100) NOT NULL,
                        especie VARCHAR2(50),
                        raca VARCHAR2(50),
                        idade NUMBER,
                        tutor_id NUMBER NOT NULL,
                        CONSTRAINT fk_pet_tutor FOREIGN KEY (tutor_id) REFERENCES tb_tutor(id)
);

-- 5. Criação do Agendamento
CREATE TABLE tb_agendamento (
                                id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                data_hora TIMESTAMP NOT NULL,
                                motivo VARCHAR2(255),
                                pet_id NUMBER NOT NULL,
                                veterinario_id NUMBER NOT NULL,
                                CONSTRAINT fk_agendamento_pet FOREIGN KEY (pet_id) REFERENCES tb_pet(id),
                                CONSTRAINT fk_agendamento_vet FOREIGN KEY (veterinario_id) REFERENCES tb_veterinario(id)
);