-- 1. Create User (Segurança)
CREATE TABLE tb_user (
                         id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                         username VARCHAR2(255) NOT NULL UNIQUE,
                         password VARCHAR2(255) NOT NULL,
                         role VARCHAR2(20) NOT NULL
);

-- 2. Create Tutor
CREATE TABLE tb_tutor (
                          id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                          nome_completo VARCHAR2(100) NOT NULL,
                          cpf VARCHAR2(14) NOT NULL UNIQUE,
                          telefone VARCHAR2(20),
                          email VARCHAR2(100) NOT NULL UNIQUE,
                          foto_url VARCHAR2(255),
                          user_id NUMBER UNIQUE,
                          logradouro VARCHAR2(255),
                          numero VARCHAR2(20),
                          bairro VARCHAR2(100),
                          cidade VARCHAR2(100),
                          estado VARCHAR2(2),
                          cep VARCHAR2(9),
                          CONSTRAINT fk_tutor_user FOREIGN KEY (user_id) REFERENCES tb_user(id)
);

-- 3. Create Clinica
CREATE TABLE tb_clinica (
                            id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                            nome VARCHAR2(100) NOT NULL,
                            cnpj VARCHAR2(20) UNIQUE,
                            telefone VARCHAR2(20),
                            email VARCHAR2(100)
);

-- 4. Create Veterinario
CREATE TABLE tb_veterinario (
                                id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                nome_completo VARCHAR2(100) NOT NULL,
                                email VARCHAR2(100) NOT NULL UNIQUE,
                                telefone VARCHAR2(20),
                                foto_url VARCHAR2(255),
                                crmv VARCHAR2(20) NOT NULL UNIQUE,
                                user_id NUMBER UNIQUE,
                                clinica_id NUMBER,
                                CONSTRAINT fk_vet_user FOREIGN KEY (user_id) REFERENCES tb_user(id),
                                CONSTRAINT fk_vet_clinica FOREIGN KEY (clinica_id) REFERENCES tb_clinica(id)
);

-- 5. Create Agenda Disponivel
CREATE TABLE tb_agenda_disponivel (
                                      id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                      data_hora_inicio TIMESTAMP NOT NULL,
                                      data_hora_fim TIMESTAMP NOT NULL,
                                      disponivel NUMBER(1) DEFAULT 1 NOT NULL,
                                      veterinario_id NUMBER NOT NULL,
                                      CONSTRAINT fk_agenda_vet FOREIGN KEY (veterinario_id) REFERENCES tb_veterinario(id)
);

-- 6. Create Pet
CREATE TABLE tb_pet (
                        id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        nome VARCHAR2(100) NOT NULL,
                        especie VARCHAR2(50),
                        raca VARCHAR2(50),
                        idade NUMBER,
                        tutor_id NUMBER NOT NULL,
                        CONSTRAINT fk_pet_tutor FOREIGN KEY (tutor_id) REFERENCES tb_tutor(id)
);

-- 7. Create Catalogo Preventivo
CREATE TABLE tb_catalogo_preventivo (
                                        id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                        especie VARCHAR2(50) NOT NULL,
                                        idade_recomendada_meses NUMBER NOT NULL,
                                        descricao_alerta VARCHAR2(255) NOT NULL
);

-- 8. Create Consulta
CREATE TABLE tb_consulta (
                             id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                             data_hora TIMESTAMP NOT NULL,
                             resumo VARCHAR2(255),
                             diagnostico VARCHAR2(255),
                             pet_id NUMBER NOT NULL,
                             veterinario_id NUMBER NOT NULL,
                             clinica_id NUMBER NOT NULL,
                             CONSTRAINT fk_consulta_pet FOREIGN KEY (pet_id) REFERENCES tb_pet(id),
                             CONSTRAINT fk_consulta_vet FOREIGN KEY (veterinario_id) REFERENCES tb_veterinario(id),
                             CONSTRAINT fk_consulta_clinica FOREIGN KEY (clinica_id) REFERENCES tb_clinica(id)
);

-- 9. Create Agendamento
CREATE TABLE tb_agendamento (
                                id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                data_hora TIMESTAMP NOT NULL,
                                titulo VARCHAR2(100),
                                descricao VARCHAR2(255),
                                consulta_id NUMBER NOT NULL,
                                CONSTRAINT fk_agendamento_consulta FOREIGN KEY (consulta_id) REFERENCES tb_consulta(id)
);

-- 10. Create Medicamento
CREATE TABLE tb_medicamento (
                                id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                nome VARCHAR2(100) NOT NULL,
                                dosagem VARCHAR2(100) NOT NULL,
                                frequencia VARCHAR2(100) NOT NULL,
                                data_inicio DATE NOT NULL,
                                duracao_dias NUMBER,
                                status VARCHAR2(20) NOT NULL,
                                consulta_id NUMBER NOT NULL,
                                CONSTRAINT fk_medicamento_consulta FOREIGN KEY (consulta_id) REFERENCES tb_consulta(id)
);

-- 11. Create Historico Dose
CREATE TABLE tb_historico_dose (
                                   id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                   data_hora_aplicacao TIMESTAMP NOT NULL,
                                   medicamento_id NUMBER NOT NULL,
                                   CONSTRAINT fk_historico_medicamento FOREIGN KEY (medicamento_id) REFERENCES tb_medicamento(id)
);